### ISSUE TITLE
FeedOptions.PartitionKey is not honored after 2.8.1 upgrade to 2.9.x with CountAsync()

### ISSUE THREAD

**Issue by stephenschwan** [Azure/azure-cosmos-dotnet-v2#757]
CountAsync() does not honor the partitionKey set in feedoptions after a nuget upgrade from 2.8.1 to 2.9.X.

**To Reproduce**
```
return await _docDbClient.CreateDocumentQuery(_collectionUri, new FeedOptions() { PartitionKey = new PartitionKey("somepartition" })
.Where(filter)
.CountAsync();
```
**Expected behavior**
Counts all entities for a partition

**Actual behavior**
Counts all entities across all partitions

**Environment summary**
x86AnyCPU, .net core 3.0

SDK Version:
2.9.X (Microsoft.Azure.DocumentDB.Core)

Related issues:
https://github.com/Azure/azure-cosmos-dotnet-v2/issues/535
https://github.com/Azure/azure-cosmos-dotnet-v2/issues/543

**Comment by j82w** [comment]
@bchong95 can you please take a look?

**Comment by reisenberger** [comment]
This appears broken in 2.9.2 across more than just `.CountAsync()`.  

`FeedOptions.PartitionKey` is also not being honoured with a query of the form:

    var query = client.CreateDocumentQuery<SomeClass>(
        _collectionUri,
        new SqlQuerySpec
        {
            QueryText = $@"<some-valid-sql-query>",
            Parameters = new SqlParameterCollection { /* parameters */ },
        },
        new FeedOptions { PartitionKey = new PartitionKey("somepartition") });

**Comment by simonvane** [comment]
@j82w @bchong95 
Any news on this?

This appears to be a pretty major issue and it's been open for 6 weeks now.
There are issues in earlier versions (see #760) that are fixed in this version but this issue prevents me from upgrading.

**Comment by j82w** [comment]
I started the release process. There should be a hotfix release out mid to end of this week.

**Comment by j82w** [comment]
[2.9.4 is released](https://www.nuget.org/packages/Microsoft.Azure.DocumentDB/2.9.4). Sorry for the delay.

**Comment by jfbarnes** [comment]
I believe we were still encountering this issue in 2.10.1 and still are after an upgrade to 2.10.3.

Exact same reproduction steps as @stephenschwan above, except we are .net core 3.1
